// Code generated by protoc-gen-go. DO NOT EDIT.
// source: moviecat.proto

package moviecat

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChannelEntry struct {
	Version              int32    `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelEntry) Reset()         { *m = ChannelEntry{} }
func (m *ChannelEntry) String() string { return proto.CompactTextString(m) }
func (*ChannelEntry) ProtoMessage()    {}
func (*ChannelEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_moviecat_223631d182a39b34, []int{0}
}
func (m *ChannelEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelEntry.Unmarshal(m, b)
}
func (m *ChannelEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelEntry.Marshal(b, m, deterministic)
}
func (dst *ChannelEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelEntry.Merge(dst, src)
}
func (m *ChannelEntry) XXX_Size() int {
	return xxx_messageInfo_ChannelEntry.Size(m)
}
func (m *ChannelEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelEntry proto.InternalMessageInfo

func (m *ChannelEntry) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ChannelEntry) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ChannelEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TopicEntry struct {
	Version              int32    `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopicEntry) Reset()         { *m = TopicEntry{} }
func (m *TopicEntry) String() string { return proto.CompactTextString(m) }
func (*TopicEntry) ProtoMessage()    {}
func (*TopicEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_moviecat_223631d182a39b34, []int{1}
}
func (m *TopicEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicEntry.Unmarshal(m, b)
}
func (m *TopicEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicEntry.Marshal(b, m, deterministic)
}
func (dst *TopicEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicEntry.Merge(dst, src)
}
func (m *TopicEntry) XXX_Size() int {
	return xxx_messageInfo_TopicEntry.Size(m)
}
func (m *TopicEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicEntry.DiscardUnknown(m)
}

var xxx_messageInfo_TopicEntry proto.InternalMessageInfo

func (m *TopicEntry) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *TopicEntry) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TopicEntry) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MovieEntry struct {
	Version              int32    `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	ChannelId            int64    `protobuf:"varint,3,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	TopicId              int64    `protobuf:"varint,4,opt,name=topic_id,json=topicId" json:"topic_id,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=title" json:"title,omitempty"`
	PublishedAt          int64    `protobuf:"varint,6,opt,name=published_at,json=publishedAt" json:"published_at,omitempty"`
	Duration             int64    `protobuf:"varint,7,opt,name=duration" json:"duration,omitempty"`
	Size                 int64    `protobuf:"varint,8,opt,name=size" json:"size,omitempty"`
	Descr                string   `protobuf:"bytes,9,opt,name=descr" json:"descr,omitempty"`
	Url                  string   `protobuf:"bytes,10,opt,name=url" json:"url,omitempty"`
	HasWebsiteUrl        bool     `protobuf:"varint,11,opt,name=has_website_url,json=hasWebsiteUrl" json:"has_website_url,omitempty"`
	HasSubtitleUrl       bool     `protobuf:"varint,12,opt,name=has_subtitle_url,json=hasSubtitleUrl" json:"has_subtitle_url,omitempty"`
	HasSmallFormatUrl    bool     `protobuf:"varint,13,opt,name=has_small_format_url,json=hasSmallFormatUrl" json:"has_small_format_url,omitempty"`
	HasHdFormatUrl       bool     `protobuf:"varint,14,opt,name=has_hd_format_url,json=hasHdFormatUrl" json:"has_hd_format_url,omitempty"`
	HasHistoryUrl        bool     `protobuf:"varint,15,opt,name=has_history_url,json=hasHistoryUrl" json:"has_history_url,omitempty"`
	Geo                  string   `protobuf:"bytes,16,opt,name=geo" json:"geo,omitempty"`
	IsNew                bool     `protobuf:"varint,17,opt,name=is_new,json=isNew" json:"is_new,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovieEntry) Reset()         { *m = MovieEntry{} }
func (m *MovieEntry) String() string { return proto.CompactTextString(m) }
func (*MovieEntry) ProtoMessage()    {}
func (*MovieEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_moviecat_223631d182a39b34, []int{2}
}
func (m *MovieEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieEntry.Unmarshal(m, b)
}
func (m *MovieEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieEntry.Marshal(b, m, deterministic)
}
func (dst *MovieEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieEntry.Merge(dst, src)
}
func (m *MovieEntry) XXX_Size() int {
	return xxx_messageInfo_MovieEntry.Size(m)
}
func (m *MovieEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieEntry.DiscardUnknown(m)
}

var xxx_messageInfo_MovieEntry proto.InternalMessageInfo

func (m *MovieEntry) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *MovieEntry) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MovieEntry) GetChannelId() int64 {
	if m != nil {
		return m.ChannelId
	}
	return 0
}

func (m *MovieEntry) GetTopicId() int64 {
	if m != nil {
		return m.TopicId
	}
	return 0
}

func (m *MovieEntry) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MovieEntry) GetPublishedAt() int64 {
	if m != nil {
		return m.PublishedAt
	}
	return 0
}

func (m *MovieEntry) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *MovieEntry) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *MovieEntry) GetDescr() string {
	if m != nil {
		return m.Descr
	}
	return ""
}

func (m *MovieEntry) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *MovieEntry) GetHasWebsiteUrl() bool {
	if m != nil {
		return m.HasWebsiteUrl
	}
	return false
}

func (m *MovieEntry) GetHasSubtitleUrl() bool {
	if m != nil {
		return m.HasSubtitleUrl
	}
	return false
}

func (m *MovieEntry) GetHasSmallFormatUrl() bool {
	if m != nil {
		return m.HasSmallFormatUrl
	}
	return false
}

func (m *MovieEntry) GetHasHdFormatUrl() bool {
	if m != nil {
		return m.HasHdFormatUrl
	}
	return false
}

func (m *MovieEntry) GetHasHistoryUrl() bool {
	if m != nil {
		return m.HasHistoryUrl
	}
	return false
}

func (m *MovieEntry) GetGeo() string {
	if m != nil {
		return m.Geo
	}
	return ""
}

func (m *MovieEntry) GetIsNew() bool {
	if m != nil {
		return m.IsNew
	}
	return false
}

type MovieCatalog struct {
	Version              int32           `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	PublishedAt          int64           `protobuf:"varint,2,opt,name=published_at,json=publishedAt" json:"published_at,omitempty"`
	Md5Hash              []byte          `protobuf:"bytes,3,opt,name=md5_hash,json=md5Hash,proto3" json:"md5_hash,omitempty"`
	Channels             []*ChannelEntry `protobuf:"bytes,4,rep,name=channels" json:"channels,omitempty"`
	Topics               []*TopicEntry   `protobuf:"bytes,5,rep,name=topics" json:"topics,omitempty"`
	Movies               []*MovieEntry   `protobuf:"bytes,6,rep,name=movies" json:"movies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MovieCatalog) Reset()         { *m = MovieCatalog{} }
func (m *MovieCatalog) String() string { return proto.CompactTextString(m) }
func (*MovieCatalog) ProtoMessage()    {}
func (*MovieCatalog) Descriptor() ([]byte, []int) {
	return fileDescriptor_moviecat_223631d182a39b34, []int{3}
}
func (m *MovieCatalog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieCatalog.Unmarshal(m, b)
}
func (m *MovieCatalog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieCatalog.Marshal(b, m, deterministic)
}
func (dst *MovieCatalog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieCatalog.Merge(dst, src)
}
func (m *MovieCatalog) XXX_Size() int {
	return xxx_messageInfo_MovieCatalog.Size(m)
}
func (m *MovieCatalog) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieCatalog.DiscardUnknown(m)
}

var xxx_messageInfo_MovieCatalog proto.InternalMessageInfo

func (m *MovieCatalog) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *MovieCatalog) GetPublishedAt() int64 {
	if m != nil {
		return m.PublishedAt
	}
	return 0
}

func (m *MovieCatalog) GetMd5Hash() []byte {
	if m != nil {
		return m.Md5Hash
	}
	return nil
}

func (m *MovieCatalog) GetChannels() []*ChannelEntry {
	if m != nil {
		return m.Channels
	}
	return nil
}

func (m *MovieCatalog) GetTopics() []*TopicEntry {
	if m != nil {
		return m.Topics
	}
	return nil
}

func (m *MovieCatalog) GetMovies() []*MovieEntry {
	if m != nil {
		return m.Movies
	}
	return nil
}

func init() {
	proto.RegisterType((*ChannelEntry)(nil), "moviecat.ChannelEntry")
	proto.RegisterType((*TopicEntry)(nil), "moviecat.TopicEntry")
	proto.RegisterType((*MovieEntry)(nil), "moviecat.MovieEntry")
	proto.RegisterType((*MovieCatalog)(nil), "moviecat.MovieCatalog")
}

func init() { proto.RegisterFile("moviecat.proto", fileDescriptor_moviecat_223631d182a39b34) }

var fileDescriptor_moviecat_223631d182a39b34 = []byte{
	// 482 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x51, 0x8b, 0xd3, 0x40,
	0x10, 0xc7, 0x49, 0xd3, 0xa4, 0xe9, 0x34, 0xd7, 0xeb, 0x2d, 0x55, 0xf6, 0x04, 0x21, 0xf6, 0x41,
	0x22, 0xc8, 0x09, 0x27, 0xf7, 0x01, 0xe4, 0x50, 0x7a, 0xa2, 0x3e, 0x44, 0xc5, 0xc7, 0xb0, 0xed,
	0xae, 0xdd, 0x85, 0x24, 0x5b, 0x76, 0xb7, 0x57, 0xce, 0x27, 0x3f, 0xb5, 0xcf, 0xb2, 0x93, 0x5c,
	0x7a, 0x54, 0x10, 0x1f, 0x7c, 0xdb, 0xf9, 0xff, 0x7f, 0x33, 0x3b, 0xcb, 0xce, 0xc0, 0xb4, 0xd6,
	0xb7, 0x4a, 0xac, 0x99, 0xbb, 0xd8, 0x1a, 0xed, 0x34, 0x49, 0xee, 0xe3, 0xc5, 0x07, 0x48, 0xaf,
	0x25, 0x6b, 0x1a, 0x51, 0xbd, 0x6d, 0x9c, 0xb9, 0x23, 0x14, 0x46, 0xb7, 0xc2, 0x58, 0xa5, 0x1b,
	0x1a, 0x64, 0x41, 0x1e, 0x15, 0xf7, 0x21, 0x99, 0xc2, 0x40, 0x71, 0x3a, 0xc8, 0x82, 0x3c, 0x2c,
	0x06, 0x8a, 0x13, 0x02, 0xc3, 0x86, 0xd5, 0x82, 0x86, 0x59, 0x90, 0x8f, 0x0b, 0x3c, 0x2f, 0xde,
	0x03, 0x7c, 0xd1, 0x5b, 0xb5, 0xfe, 0x1f, 0xb5, 0x7e, 0x0e, 0x01, 0x3e, 0xfa, 0x36, 0xff, 0xbd,
	0xd8, 0x18, 0x8b, 0x3d, 0x05, 0x58, 0xb7, 0x4f, 0x2a, 0x15, 0xc7, 0x92, 0x61, 0x31, 0xee, 0x94,
	0x1b, 0x4e, 0xce, 0x21, 0x71, 0xbe, 0x47, 0x6f, 0x0e, 0xd1, 0x1c, 0x61, 0x7c, 0xc3, 0xc9, 0x1c,
	0x22, 0xa7, 0x5c, 0x25, 0x68, 0x84, 0xc5, 0xda, 0x80, 0x3c, 0x83, 0x74, 0xbb, 0x5b, 0x55, 0xca,
	0x4a, 0xc1, 0x4b, 0xe6, 0x68, 0x8c, 0x49, 0x93, 0x5e, 0x7b, 0xe3, 0xc8, 0x13, 0x48, 0xf8, 0xce,
	0x30, 0xe7, 0xbb, 0x1b, 0xa1, 0xdd, 0xc7, 0xfe, 0x6d, 0x56, 0xfd, 0x10, 0x34, 0x41, 0x1d, 0xcf,
	0xfe, 0x22, 0x2e, 0xec, 0xda, 0xd0, 0x71, 0x7b, 0x11, 0x06, 0x64, 0x06, 0xe1, 0xce, 0x54, 0x14,
	0x50, 0xf3, 0x47, 0xf2, 0x1c, 0x4e, 0x25, 0xb3, 0xe5, 0x5e, 0xac, 0xac, 0x72, 0xa2, 0xf4, 0xee,
	0x24, 0x0b, 0xf2, 0xa4, 0x38, 0x91, 0xcc, 0x7e, 0x6b, 0xd5, 0xaf, 0xa6, 0x22, 0x39, 0xcc, 0x3c,
	0x67, 0x77, 0x2b, 0x6c, 0x19, 0xc1, 0x14, 0xc1, 0xa9, 0x64, 0xf6, 0x73, 0x27, 0x7b, 0xf2, 0x15,
	0xcc, 0x91, 0xac, 0x59, 0x55, 0x95, 0xdf, 0xb5, 0xa9, 0x99, 0x43, 0xfa, 0x04, 0xe9, 0x33, 0x4f,
	0x7b, 0xeb, 0x1d, 0x3a, 0x3e, 0xe1, 0x05, 0x78, 0xb1, 0x94, 0xfc, 0x21, 0x3d, 0xed, 0x6b, 0x2f,
	0xf9, 0x01, 0xed, 0xba, 0x95, 0xca, 0x3a, 0x6d, 0xee, 0x10, 0x3c, 0xed, 0xbb, 0x5d, 0xb6, 0xaa,
	0xe7, 0x66, 0x10, 0x6e, 0x84, 0xa6, 0xb3, 0xf6, 0x9d, 0x1b, 0xa1, 0xc9, 0x23, 0x88, 0x95, 0x2d,
	0x1b, 0xb1, 0xa7, 0x67, 0x98, 0x10, 0x29, 0xfb, 0x49, 0xec, 0x17, 0xbf, 0x02, 0x48, 0x71, 0x04,
	0xae, 0x99, 0x63, 0x95, 0xde, 0xfc, 0x65, 0x08, 0x8e, 0x3f, 0x69, 0xf0, 0xe7, 0x27, 0x9d, 0x43,
	0x52, 0xf3, 0xab, 0x52, 0x32, 0x2b, 0x71, 0x2a, 0xd2, 0x62, 0x54, 0xf3, 0xab, 0x25, 0xb3, 0x92,
	0x5c, 0x42, 0xd2, 0x0d, 0x88, 0xa5, 0xc3, 0x2c, 0xcc, 0x27, 0x97, 0x8f, 0x2f, 0xfa, 0x95, 0x79,
	0xb8, 0x1f, 0x45, 0xcf, 0x91, 0x97, 0x10, 0xe3, 0xdc, 0x58, 0x1a, 0x61, 0xc6, 0xfc, 0x90, 0x71,
	0xd8, 0x81, 0xa2, 0x63, 0x3c, 0x8d, 0xb6, 0xa5, 0xf1, 0x31, 0x7d, 0x18, 0xf2, 0xa2, 0x63, 0x56,
	0x31, 0xae, 0xe9, 0xeb, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6a, 0xdc, 0x58, 0x85, 0xb8, 0x03,
	0x00, 0x00,
}
